# .goreleaser.yaml
builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

archives:
  - format: binary

checksum:
  name_template: 'checksums.txt'
signs:
  - artifacts: checksum
    args: ["--output", "${signature}", "--detach-sign", "--local-user", "${gpg_key_id}", "${artifact}"]